-- 1. Profiles Table
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  email TEXT UNIQUE,
  phone TEXT,
  department TEXT,
  year TEXT,
  role TEXT DEFAULT 'student',
  membership_status TEXT DEFAULT 'inactive',
  membership_expiry TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Trainers Table
CREATE TABLE trainers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  specialization TEXT,
  bio TEXT,
  experience TEXT,
  rating FLOAT DEFAULT 5.0,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Membership Plans Table
CREATE TABLE membership_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price FLOAT NOT NULL,
  period TEXT NOT NULL,
  description TEXT,
  features TEXT[], -- Array of features
  highlight BOOLEAN DEFAULT FALSE,
  icon TEXT, -- e.g., 'Zap', 'Star', 'ShieldCheck'
  theme TEXT, -- CSS classes
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Classes Table
CREATE TABLE classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT,
  duration TEXT,
  schedule TEXT,
  trainer_id BIGINT REFERENCES trainers(id) ON DELETE SET NULL,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Slots Table
CREATE TABLE slots (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  session TEXT CHECK (session IN ('morning', 'evening')),
  slot_number INT,
  time TEXT,
  capacity INT DEFAULT 30,
  booked INT DEFAULT 0,
  date DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Bookings Table
CREATE TABLE bookings (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  slot_id UUID REFERENCES slots(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Subscriptions Table
CREATE TABLE subscriptions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  plan_id BIGINT REFERENCES membership_plans(id) ON DELETE CASCADE,
  start_date TIMESTAMPTZ NOT NULL,
  end_date TIMESTAMPTZ NOT NULL,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Payments Table
CREATE TABLE payments (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  subscription_id UUID REFERENCES subscriptions(id) ON DELETE CASCADE,
  amount FLOAT NOT NULL,
  status TEXT DEFAULT 'completed',
  payment_date TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Progress Table
CREATE TABLE progress (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  weight FLOAT NOT NULL,
  date TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Announcements Table
CREATE TABLE announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Initial Data Seeds
-- Insert Plans
INSERT INTO membership_plans (name, price, period, description, features, highlight, icon, theme) VALUES
('Student Basic', 199, 'month', 'Ideal for beginners and regular student fitness enthusiasts.', '{"Access to cardio zone", "Full locker access", "Basic training guidance", "Valid for 30 days"}', FALSE, 'Zap', 'border-border shadow-sm'),
('Elite Performance', 499, '3 months', 'Most popular choice for dedicated student athletes.', '{"Full gym equipment access", "Personal nutrition advice", "2 Priority slot bookings", "Progress tracking tools", "Exclusive workshops"}', TRUE, 'Star', 'border-primary/50 shadow-xl bg-primary/5 dark:bg-primary/10'),
('Annual Guardian', 1499, 'year', 'Best value for long-term health and commitment.', '{"All Elite features included", "Access to summer camps", "Personal trainer assigned", "Guest pass for 2 friends/month", "Free RIT Gym t-shirt"}', FALSE, 'ShieldCheck', 'border-border shadow-md');

-- Insert Trainers
INSERT INTO trainers (full_name, specialization, experience, bio) VALUES
('Rahul Sharma', 'Strength & Conditioning', '5 Years', 'Certified expert in powerlifting and body transformation.'),
('Priya Patil', 'Yoga & Wellness', '4 Years', 'Helping students achieve mental and physical balance through yoga.');

-- Insert Slots for Today/Tomorrow (Optional manual)
-- INSERT INTO slots (session, slot_number, time, capacity, date) VALUES 
-- ('morning', 1, '6:00 AM - 7:30 AM', 30, CURRENT_DATE),
-- ('morning', 2, '7:30 AM - 9:00 AM', 30, CURRENT_DATE);

-- RLS Policies (Basic)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone." ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON profiles FOR UPDATE USING (auth.uid() = id);

ALTER TABLE membership_plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Plans are viewable by everyone." ON membership_plans FOR SELECT USING (true);

ALTER TABLE trainers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Trainers are viewable by everyone." ON trainers FOR SELECT USING (true);

ALTER TABLE classes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Classes are viewable by everyone." ON classes FOR SELECT USING (true);

ALTER TABLE slots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Slots are viewable by everyone." ON slots FOR SELECT USING (true);

ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own bookings." ON bookings FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own bookings." ON bookings FOR INSERT WITH CHECK (auth.uid() = user_id);

ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own subscriptions." ON subscriptions FOR SELECT USING (auth.uid() = user_id);

ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own payments." ON payments FOR SELECT USING (auth.uid() = user_id);

ALTER TABLE progress ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own progress." ON progress FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own progress." ON progress FOR INSERT WITH CHECK (auth.uid() = user_id);

ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Announcements are viewable by everyone." ON announcements FOR SELECT USING (true);
